feat: create and send event about what happened
ocadotechnology/kubernetes-chaosmonkey pull request #1
Opened 2017-06-12 09:35 UTC by Godley

Persists chaos monkey deletion to event layer for easy assessing of whether the chaos monkey caused the problem or something else.
Still to test this locally, but in theory this should be ok.

2017-06-12 12:26 UTC, mikebryant requested changes
Looks good.
We should definitely test it locally before merge though

2017-06-12 12:26 UTC, mikebryant commented on chaos.py
> +        type="Warning"
nitpick: Add trailing comma?

2017-06-12 12:26 UTC, mikebryant commented on chaos.py
> +            uid=pod.metadata.uid
nitpick: trailing comma

2017-06-12 16:13 UTC, Godley commented
@mikebryant tested on minikube, just one problem with the event not having a name then it seems to be working fine.

2017-06-12 17:06 UTC, Godley commented
I'm getting "Event in version \"v1\" cannot be handled as a Event: only encoded map or array can be decoded into a struct" when I try to create the event from the exception handler. Completely non-plussed as to why.

2017-06-13 10:25 UTC, Godley commented
@mikebryant should be all good now

2017-06-13 11:25 UTC, mikebryant commented
LGTM
Can we squash that last fix commit?

2017-06-13 11:25 UTC, mikebryant commented
and also the style commits etc

2017-06-13 11:26 UTC, Godley commented
Sure, I'm not sure how to merge commits into each other though?

2017-06-13 11:35 UTC, mikebryant approved these changes

2017-06-13 11:35 UTC, merged